export const PAYMENT_BUTTONS = [
  {
    id: 1,
    icon: "/myPay/public/assets/paymentImages/mobilOp.png",
    heading: "Mobil Operatorlar",
    url: "/operator",
    iconBg: "rgba(55, 191, 254, 0.1)",
  },
  {
    id: 2,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "İnternet",
    url: "/internet",
    iconBg: "rgba(255, 54, 131, 0.1)",
  },
  {
    id: 3,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "Komunal xidmətlər",
    url: "/kommunal",
    iconBg: "rgba(254, 144, 1, 0.1)",
  },
  {
    id: 4,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "Telefon",
    url: "/phone",
    iconBg: "rgba(55, 191, 254, 0.1)",
  },
  {
    id: 5,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "TV",
    url: "/tv",
    iconBg: "rgba(139, 97, 244, 0.1)",
  },
  {
    id: 6,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "İnzibati cərimə ödənişləri",
    url: "/adminpay",
    iconBg: "rgba(66, 218, 94, 0.1)",
  },
  {
    id: 7,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "Əyləncə",
    url: "/fun",
    iconBg: "rgba(139, 97, 244, 0.1)",
  },
  {
    id: 8,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "Bank xidmәtlәri, Sığorta",
    url: "/bank",
    iconBg: "rgba(61, 184, 104, 0.1)",
  },
  {
    id: 9,
    icon: "../../assets/paymentImages/mobOperator.svg",
    heading: "Digər",
    url: "/about",
    iconBg: "rgba(55, 191, 254, 0.1)",
  },
];
